modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/ShadowKing21228/RegeneratingBlocks/issues"
license = "All Rights Reserved"

[[mods]]
modId = "regeneratingblocks"
version = "${version}"
displayName = "Regenerating Blocks"
authors = "ShadowKing21"
description = '''
Mod that adds a regeneratig block, which can morph to any other block - to refill ores in maps or servers.
'''
#logoFile = ""

[[dependencies.regeneratingblocks]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.regeneratingblocks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.regeneratingblocks]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.regeneratingblocks]]
modId="shadowconfig"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.regeneratingblocks]]
modId="jade"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"